# Generated by Django 4.2.11 on 2024-03-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('everyday', 'Everyday Services'), ('premierservice', 'Premier Services'), ('shortening', 'Shortening Services'), ('zip', 'New Zip Services'), ('resize', 'Resizing Services'), ('misc', 'Miscellaneous Services'), ('household', 'Household Services'), ('formal', 'Formal Wear Services'), ('leather/suede', 'Leather/Suede Services'), ('misc', 'Miscellaneous Services')], max_length=255)),
                ('tag', models.CharField(choices=[('dryclean', 'Everyday Services'), ('laundry', 'Laundry Services'), ('tailoring', 'Tailoring Services'), ('specialist', 'Specialists Services')], max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dryClean.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dryClean.user')),
            ],
        ),
    ]
