# Generated by Django 4.2.11 on 2024-03-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryClean', '0002_rename_date_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
